config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "posts#index"

  resources :users, only: [:show, :edit, :update] do 
    member do 
      patch :accept_friendship
    end
  end

  resources :posts do
  	resources :comments, shallow: true
  	member do 
  		post :add_collection
  		delete :remove_collection
    end
    collection do
      get :feeds
    end
  end

  resources :friendships, only: [:create, :destroy]

  scope '/admin' do
    resources :categories, only: [:index, :create, :update, :destroy]
    patch '/users/:id', to: 'users#update_admin', as: :update_admin
    get '/users', to: 'users#index'
    # resources :users, only: [:index, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
	
	mount_uploader :avatar, AvatarUploader

	has_many :posts, foreign_key: "author_id", dependent: :destroy
	has_many :published_posts, -> { where published: true }, :class_name => "Post", :foreign_key => "author_id"
	has_many :unpublished_posts, -> { where published: false }, :class_name => "Post", :foreign_key => "author_id"
	
	has_many :comments, dependent: :destroy
	has_many :commented_posts, through: :comments, source: :post

	#unapproved
	has_many :unapproved_friending, -> { where(approved: false) }, :class_name => "Friendship", :foreign_key => "sender_id"
	has_many :friends_to_be_approved, through: :unapproved_friending, source: :receiver

	has_many :unapproved_friended, -> { where(approved: false) }, class_name: "Friendship", foreign_key: "receiver_id"
	has_many :friends_to_approve, through: :unapproved_friended, source: :sender

	#approved
	has_many :approved_friending, -> { where(approved: true) }, :class_name => "Friendship", :foreign_key => "sender_id"
	has_many :accepted_friends, through: :approved_friending, source: :receiver

	has_many :approved_friended, -> { where(approved: true) }, class_name: "Friendship", foreign_key: "receiver_id"
	has_many :approved_friends, through: :approved_friended, source: :sender

	has_many :collections, dependent: :destroy
	has_many :collected_posts, through: :collections, source: :post

	def friends
		self.accepted_friends + self.approved_friends
	end
	
	def friend_with?(user)
		self.accepted_friends.include?(user) or self.approved_friends.include?(user)
	end

	def admin?
		self.admin
	end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :set_user, :only => [:show, :edit, :update, :update_admin]
	def index
		@users = User.all
	end

	def show
		@user_published_posts = @user.published_posts
		@user_comments = @user.comments
		@user_unpublished_posts = @user.unpublished_posts
		@user_collected_posts = @user.collected_posts
		@friends_to_be_approved = @user.friends_to_be_approved
		@friends_to_approve = @user.friends_to_approve
		@friends = @user.accepted_friends + @user.approved_friends
	end

	def accept_friendship
		@friendship = current_user.unapproved_friended.where({ sender_Id: params[:id]})
		@friendship.update(approved: true)
		respond_to :js, :html
	end

	def ignore_friendship
	end

	def edit
	end 

	def update
		@user.update(user_params)
		redirect_to user_path(@user)
	end

	def update_admin
		@user.update(admin_user_params)
		redirect_to users_path
	end

	private

	def user_params
		params.require(:user).permit(:description, :avatar)
	end

	def admin_user_params
		params.permit(:admin)
	end

	def set_user
		@user = User.find_by(id: params[:id])
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
	<div class="row user_profile">
		<div class="col-md-12">
			<%= form_with model: @user, method: :patch do |f| %>
				<div class="form-group">
					<h4><%= @user.firstname%> <%= @user.lastname%></h4>
				</div>
				<div class="form-group">
					<%= image_tag @user.avatar.url, size: "100x100", class: "d-block" %>
					<%= f.file_field :avatar %>
				</div>
				<div class="form-group">
					<%= f.label :description %>
					<%= f.text_area(:description, :class => "user-profile-description") %>
				</div>
				<div class="form-group">
					<%= f.submit class: 'btn btn-info btn-sm' %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="table">
                <div class="row">
                    <div class="col-md-4"><b>Name</b></div>
                    <div class="col-md-4"><b>Email</b></div>
                    <div class="col-md-4"><b>Role</b></div>
                </div>
                <% @users.each do |u| %>
                <div class="row user-admin-row">
                    <div class="col-md-4"><%= u.firstname%> <%= u.lastname%></div>
                    <div class="col-md-4"><%= u.email%></div>
                    <div class="col-md-4">
                        <%= form_tag update_admin_path(u), method: :patch do %>
                            <%= select_tag :admin, options_for_select([['Admin user', true], ['Normal user', false]], u.admin.to_s) %>
                            <%= submit_tag 'Update', class: "btn btn-sm btn-primary" %>
                        <% end %>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
	<div class="row user_profile">
		<div class="col-md-2">
			<%= image_tag @user.avatar.url, size: "100x100", class: "d-block"%>
			<h5><%= @user.firstname%> <%= @user.lastname%></h5>
			<%= render partial: "shared/add_button", locals: { user: @user, related_user: current_user} %>
		</div>
		<div class="col-md-10">
			<p><%= truncate(@user.description, length: 400) %></p>
			<% if @user == current_user %>
				<%= link_to "Edit Porfile", edit_user_path, class: 'btn btn-info btn-sm' %>
			<% end %>
		</div>`
	</div>
	<ul class="nav nav-tabs" id="myTab" role="tablist">
	  <li class="nav-item">
	    <a class="nav-link active" id="Post-tab" data-toggle="tab" href="#Post" role="tab" aria-controls="Post" aria-selected="true">Post</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="comment-tab" data-toggle="tab" href="#comment" role="tab" aria-controls="comment" aria-selected="false">Comment</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="collection-tab" data-toggle="tab" href="#collection" role="tab" aria-controls="collection" aria-selected="false">Collection</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="draft-tab" data-toggle="tab" href="#draft" role="tab" aria-controls="draft" aria-selected="false">Draft</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="friend-tab" data-toggle="tab" href="#friend" role="tab" aria-controls="friend" aria-selected="false">Friend</a>
	  </li>
	</ul>
	<div class="row">
		<div class="col-md-12">
			<div class="tab-content" id="myTabContent">
			  <div class="tab-pane fade show active" id="Post" role="tabpanel" aria-labelledby="Post-tab">
			  	<br>
			  	<table class="table table-striped">
			  		<thead>
			  			<tr>
			  				<th scope="col">Title</th>
			  				<th scope="col">Published date</th>
			  				<th scope="col">Brief</th>
			  			</tr>
			  		</thead>
			  		<tbody>
				  		<% @user_published_posts.each do |p| %>
					  		<tr>
					  			<td><%= link_to "#{p.title}", post_path(p) %></td>
					  			<td><%= p.updated_at %></td>
					  			<td><%= truncate(p.content) %></td>
					  		</tr>
					  	<% end %>
					</tbody>
			  	</table>
			  	
			  </div>
			  <div class="tab-pane fade" id="comment" role="tabpanel" aria-labelledby="comment-tab">
			  	<table class="table table-striped">
			  		<br>
			  		<thead>
			  			<tr>
			  				<th scope="col">Post Title</th>
			  				<th scope="col">Comment</th>
			  			</tr>
			  		</thead>
			  		<tbody>
					  	<% @user_comments.each do |c| %>
							<tr>
					  			<td><%= link_to "#{c.post.title}", post_path(c) %></td>
					  			<td><%= truncate(c.content) %></td>
						  	</tr>
					  	<% end %>
					</tbody>
			  	</table>
			  </div>
			  <div class="tab-pane fade" id="collection" role="tabpanel" aria-labelledby="collection-tab">
			  	<table class="table table-striped">
			  		<br>
			  		<thead>
			  			<tr>
			  				<th scope="col">Post Title</th>
			  				<th scope="col">Action</th>
			  			</tr>
			  		</thead>
			  		<tbody>
			  			<% @user_collected_posts.each do |p| %>
			  				<tr>
				  				<td><%= link_to "#{p.title}", post_path(p) %></td>
				  				<td><span class="btn btn-danger btn-sm uncollect-post" id="<%= p.id %>" >Uncollect</span></td>
				  			</tr>
			  			<% end %>
			  		</tbody>
			  	</table>
			  </div>
			  <div class="tab-pane fade" id="draft" role="tabpanel" aria-labelledby="draft-tab">
			  	<br>
			  	<table class="table table-striped">
			  		<thead>
			  			<tr>
			  				<th scope="col">Title</th>
			  				<th scope="col">Created date</th>
			  			</tr>
			  		</thead>
			  		<tbody>
				  		<% @user_unpublished_posts.each do |p| %>
					  		<tr>
					  			<td><%= link_to "#{p.title}", edit_post_path(p) %></td>
					  			<td><%= p.created_at %></td>
					  		</tr>
					  	<% end %>
					</tbody>
			  	</table>
			  </div>
			  <div class="tab-pane fade" id="friend" role="tabpanel" aria-labelledby="friend-tab">
			  	<br>
			  	<% if @user == current_user %>
				  	<h5>Waiting for Response</h5>
				  	<div class="row">
				  		<div class="col-md-12">
					  		<% @friends_to_be_approved.each do |f| %>
					  			<div class="card text-center user-card align-middle">
						  			<%= render partial: "shared/user_icon", locals: {user: f, related_user: @user} %>
						  		</div>
					  		<% end %>
					  	</div>
				  	</div>
				  	<hr>
				  	<h5>Friend Request</h5>
				  	<div class="row">
				  		<div class="col-md-12">
					  		<% @friends_to_approve.each do |f| %>
					  			<div class="card text-center user-card" id="<%= f.id %>">
					  				<%= render partial: "shared/user_icon", locals: {user: f, related_user: @user} %>
					  			</div>
					  		<% end %>
					  	</div>
				  	</div>
				  	<hr>
				<% end %>
			  	<h5>Friend List</h5>
			  	<div class="row">
			  		<div class="col-md-12">
				  		<% @friends.each do |f| %>
				  			<div class="card text-center user-card">
				  				<%= render partial: "shared/user_icon", locals: {user: f, related_user: @user} %>
				  			</div>
				  		<% end %>
				  	</div>
			  	</div>
			  </div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(".accept-invitation").on("click", function(event) {
		
		var id = event.target.parentNode.id;
		$.ajax({
			url: id +"/accept_friendship" ,
			method: "PATCH",
			dataType: "json",
			success: function(){
				// $("#" +id).remove();
				// console.log("Card removed");
				$(".button-"+id).addClass("disabled");
			}
		});
	});
	$(".uncollect-post").on("click", function(event) {
		var post = event.target.parentNode.parentNode;
		var id = event.target.id;
		$.ajax({
			url: '/posts/' + id + '/remove_collection',
			method: 'DELETE',
			dataType: 'json',
			success: function(){
				post.remove();
			}
		})
	});
</script>