config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "posts#index"

  resources :users, only: [:show, :edit, :update] do 
    member do 
      patch :accept_friendship
    end
  end

  resources :posts do
  	resources :comments, shallow: true
  	member do 
  		post :add_collection
  		delete :remove_collection
    end
    collection do
      get :feeds
    end
  end

  resources :friendships, only: [:create, :destroy]

  scope '/admin' do
    resources :categories, only: [:index, :create, :update, :destroy]
    patch '/users/:id', to: 'users#update_admin', as: :update_admin
    get '/users', to: 'users#index'
    # resources :users, only: [:index, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

end

app/views/shared/_add_button.html.erb
<% unless user == related_user or user.friend_with?(related_user) %>
	<% if related_user.friends_to_be_approved.include?(user) %>
		<%= button_to "Request Sent", {}, disabled: true, class: 'btn btn-light btn-sm' %>
	<% elsif related_user.friends_to_approve.include?(user)%>
		<span class="btn btn-success btn-sm accept-invitation button-<%= user.id %>">Accept Invitation</span>
	<% else %>
		<%= button_to "Add Friend", friendships_path(receiver_id: user), method: :post, class: 'btn btn-light btn-sm' %>
	<% end %>
<% end %>

app/views/shared/_friendButtons.html.erb
<% unless user == current_user or user.friend_with?(current_user) %>
	<% if current_user.friends_to_be_approved.include?(user) %>
		<%= button_to "Request Sent", {}, disabled: true, class: 'btn btn-light btn-sm' %>
	<% elsif current_user.friends_to_approve.include?(user)%>
		<%= button_to "Accept Invitation", friendship_path(user), method: :patch, class: 'btn btn-light btn-sm' %>
	<% else %>
		<%= button_to "Add Friend", friendships_path(receiver_id: user), method: :post, class: 'btn btn-light btn-sm' %>
	<% end %>
<% end %>

app/views/shared/_user_icon.html.erb
<%= image_tag user.avatar.url, size: "50x50", class: "d-block mx-auto"%>
<%= link_to "#{user.firstname} #{user.lastname}", user_path(id: user) %>
<% unless user == related_user or user.friend_with?(related_user) %>
	<% if related_user.friends_to_be_approved.include?(user) %>
		<%= button_to "Request Sent", {}, disabled: true, class: 'btn btn-light btn-sm' %>
	<% elsif related_user.friends_to_approve.include?(user)%>
		<span class="btn btn-success btn-sm accept-invitation button-<%= user.id %>">Accept Invitation</span>
	<% else %>
		<%= button_to "Add Friend", friendships_path(receiver_id: user), method: :post, class: 'btn btn-light btn-sm' %>
	<% end %>
<% end %>

		