config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "posts#index"

  resources :users, only: [:show, :edit, :update] do 
    member do 
      patch :accept_friendship
    end
  end

  resources :posts do
  	resources :comments, shallow: true
  	member do 
  		post :add_collection
  		delete :remove_collection
    end
    collection do
      get :feeds
    end
  end

  resources :friendships, only: [:create, :destroy]

  scope '/admin' do
    resources :categories, only: [:index, :create, :update, :destroy]
    patch '/users/:id', to: 'users#update_admin', as: :update_admin
    get '/users', to: 'users#index'
    # resources :users, only: [:index, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

end

app/models/post.rb
class Post < ApplicationRecord
	validates_presence_of :title, :content
	
	mount_uploader :attachment, AttachmentUploader

	is_impressionable

	belongs_to :author, :class_name => "User", :foreign_key => "author_id"

	has_many :post_category_mappings, dependent: :destroy
	has_many :categories, through: :post_category_mappings
	has_many :comments, dependent: :destroy
	has_many :commented_user, through: :comments, source: :user

	#for creating post category mapping in post new action
	accepts_nested_attributes_for :categories

	has_many :collections
	has_many :collected_user, through: :collections, source: :user

	def self.readable_by_everyone
		Post.where(published: true, privacy: "all")
	end


	def self.readable_by(user)
		Post.where(published: true, privacy: "all").or(
			where(published: true, privacy: "myself", author_id: user.id)).or(
			where(published: true, privacy: "friend", author_id: user.friends))
	end

	def commented?
		return self.comments != []
	end

	def published?
		return self.published
	end

end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApiController    
    before_action :authenticate_user!, :except => [:index]
    before_action :set_post, :only => [:show, :update, :destroy]

    def index
        @posts = Post.all
        render json: {
            data: @posts
        }
    end

    def show
        if !@post
            render json: {
                message: "Can't find the photo!",
                status: 400
            }
        else
            render json: {
                data: @post
            }
        end
    end

    def create
        @post = Post.new(post_params)
        @categories = params[:categories].split(",")
        puts "Categories are #{@categories}"
        if @post.save
            @categories.each { |c|
				c.to_i
				@post.post_category_mappings.create([
					{category_id: c}
                ])
			}
            render json: {
                message: "Post created successfully",
                result: @post
            }
        else
            render json: {
                errors: @post.errors 
            }
        end
    end

    def update
        @categories = params[:categories].split(",")
        if @post.update(post_params)
            @post.post_category_mappings.destroy_all
            @categories.each { |c|
				c.to_i
				@post.post_category_mappings.create([
					{category_id: c}
                ])
			}
            render json: {
                message: "Post updated successfully",
                result: @post
            }
        else
            render json: {
                errors: @post.errors 
            }
        end
    end

    def destroy
        if @post.destroy
            render json: {
                message: "Post #{@post.id} is deleted."
            }
        else
            render json: {
                errors: @post.errors
            }
        end

    end

    private
    def post_params
        params.permit(:title, :content, :author_id, :published, :privacy, :attachment, categories: [:ids])
    end

    def set_post
        @post = Post.find_by(id: params[:id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, :except => [:index]
	before_action :set_post, :only => [:show, :destroy, :edit, :update]
	impressionist :actions => [:show]

	def index
		if current_user == nil
			# when user is visitor
			params[:category_id] ? @posts = Post.readable_by_everyone().joins(:post_category_mappings).where("post_category_mappings.category_id" => params[:category_id] )
			:  @posts = Post.readable_by_everyone()
		else
			params[:category_id] ? @posts = Post.readable_by(current_user).joins(:post_category_mappings).where("post_category_mappings.category_id" => params[:category_id] ) 
			:  @posts = Post.readable_by(current_user)
		end
		@categories = Category.all
	end

	def new
		@post = Post.new()
		@categories = Category.all
	end

	def create
		@post = current_user.posts.build(post_params)
		
		@categories = params[:category][:id]

		params[:commit] == "Create Post" ? @post.published = true : @post.published = false

		# create post category mapping from the selected categories
		if @post.save
			@categories.each { |c|
				c.to_i
				@post.post_category_mappings.create([
					{category_id: c}
				])
			}
		else
			logger.debug "#{@post.errors.full_messages.to_sentence}"
		end

		#todo: if stash, redirect to user profile
		redirect_to posts_path
	end

	def show
		@comments = @post.comments.limit(20)
	end

	def destroy
		@post.destroy
		redirect_to posts_path
	end

	def edit
	end

	def update
		if params[:commit] == "Create Post" 
			@post.published = true 
			@post.update(post_params)
			redirect_to post_path(@post)
		elsif params[:commit] == "Save Draft" 
			@post.published = false
			@post.update(post_params)
			redirect_back fallback_location: posts_path
		end
	end

	def add_collection
		@collection = current_user.collections.build(post_id: params[:id])
		@collection.save!
		respond_to :js, :html
	end

	def remove_collection
		@collection = current_user.collections.where({post_id: params[:id]})
		@collection.destroy_all
		respond_to :js, :html
	end

	def feeds
		@user_count = User.count
		@post_count = Post.count
		@comment_count = Comment.count
		@top_users = User.joins(:comments).select('users.*, COUNT(comments.id) as count').group('users.id').order('count DESC').limit(10)
		@top_posts = Post.joins(:comments).select('posts.*, COUNT(comments.id) as count').group('posts.id').order('count DESC').limit(10)
	end

	private
	def post_params
		params.require(:post).permit(:title, :content, :privacy, :attachment, categories_attributes: [:category_id])
	end

	def set_post
		@post = Post.find_by(id: params[:id])
	end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container">
	<div class="col-md-12">
		<%= form_for @post do |post| %>
				<%= post.label :title, class: "post_input_header" %><br>
				<%= post.text_field :title, class: "post_title_input" %><br>
			
				<%= post.label :content, "Post Content", class: "post_input_header" %><br>
				<%= post.text_area :content, class: "post_content_input" %><br>

				<%= post.label :privacy, class: "post_input_header" %>
				<%= post.label :all %> <%= post.radio_button :privacy, "all" %>
				<%= post.label :friend %> <%= post.radio_button :privacy, "friend" %>
				<%= post.label :myself %> <%= post.radio_button :privacy, "myself" %><br>
			
				<%#= post.label :category, class: "post_input_header" %> <%#= collection_check_boxes :category, :id, @categories, :id, :name%>
			
				<%= post.label :attachment, class: "post_input_header" %>: <%= post.file_field :attachment %><br>
			
			<%= post.submit "Save Draft", class: "btn btn-primary" %>
			<%= post.submit "Create Post", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/posts/feeds.html.erb
<div class="container">
    <br>
    <div class="row">
        <div class="col-md-4">
            <h4>User</h4>
            <%= @user_count %>
        </div>
        <div class="col-md-4">
            <h4>Post</h4>
            <%= @post_count %>
        </div>
        <div class="col-md-4">
            <h4>Comment</h4>
            <%= @comment_count %>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-6">
            <table class="table">
                <thead>
                    <tr>
                        <th>Top User Name</th>
                        <th>Comment Count</th>
                    </tr>
                </thead>
                <tbody>
                <% @top_users.each do |tu| %>
                    <tr>
                        <td><%= tu.firstname%></td>
                        <td><%= tu.count%></td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
        <div class="col-md-6">
            <table class="table">
                <thead>
                    <tr>
                        <th>Top Post Name</th>
                        <th>Comment Count</th>
                    </tr>
                </thead>
                <tbody>
                <% @top_posts.each do |tp| %>
                    <tr>
                        <td><%= truncate(tp.title, length:20)%></td>
                        <td><%= tp.count%></td>
                    </tr>
                <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
		<span>Category Lists: </span>
			<% @categories.each do |cat| %>
				<%= link_to cat.name, posts_path(category_id: cat.id), class: "btn btn-default"%>
			<% end %>
		</div>
		<div class="col-md-12">
			<table data-pagination="true" data-page-size=20 data-page-list=[10,20,all] data-toggle="table">
				<thead>
					<tr>
						<th data-sortable="true" scope="col">Replies Count</th>
						<th data-sortable="true" scope="col">Title</th>
						<th data-sortable="true" scope="col">Last replied at</th>
						<th data-sortable="true" scope="col">View Count</th>
					</tr>
				</thead>
				<tbody>
					<% @posts.each do |post|%>
						<tr>
							<td><%= post.comments.count%></td>
							<td><%= link_to post.title, post_path(post) %></td>
							<td><% if post.commented? %><%= post.comments.order(created_at: :desc).first.created_at %><% end %></td>
							<td><%= post.impressionist_count(:filter=>:user_id)%></td>
						</tr>
					<%end%>
				</tbody>
			</table>
		</div>
	</div>
</div>
<script>
	$(document).on('turbolinks:load', function() {
        $('[data-toggle="table"]').bootstrapTable();
    });
</script>

app/views/posts/new.html.erb
<div class="container">
	<div class="col-md-12">
		<%= form_for @post do |post| %>
				<%= post.label :title, class: "post_input_header" %><br>
				<%= post.text_field :title, class: "post_title_input" %><br>
			
				<%= post.label :content, "Post Content", class: "post_input_header" %><br>
				<%= post.text_area :content, class: "post_content_input" %><br>

				<%= post.label :privacy, class: "post_input_header" %>:
				<%= post.label :all %> <%= post.radio_button :privacy, "all" %>
				<%= post.label :friend %> <%= post.radio_button :privacy, "friend" %>
				<%= post.label :myself %> <%= post.radio_button :privacy, "myself" %><br>
			
				<%= post.label :category, class: "post_input_header" %>: <%= collection_check_boxes :category, :id, @categories, :id, :name%><br>
			
				<%= post.label :attachment, class: "post_input_header" %>: <%= post.file_field :attachment %><br>
			
			<%= post.submit "Save Draft", class: "btn btn-primary" %>
			<%= post.submit "Create Post", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h3><%= @post.title %></h3>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12" id="<%= @post.id %>">
			<% if not current_user.collected_posts.include?(@post)%>
				<span class="btn btn-primary btn-sm collect-post">Collect</span>
			<% else %>
				<span class="btn btn-danger btn-sm uncollect-post">Uncollect</span>
			<% end %>
		</div>
	</div>
	<div class="row post_show_entry">
		<div class="col-md-2 post_show_user" id="<%= @post.author.id %>">
			<%= render partial: "shared/user_icon", locals: { user: @post.author, related_user: current_user} %>
		</div>
		<div class="col-md-10">
			<div class="row">
				<div class="col-md-10 post_show_content">
					<%= @post.content%><br>
					<% if @post.attachment.present? %><%= image_tag @post.attachment.url, class: "img_responsive" %><% end %>
				</div>
				<div class="col-md-2">
					<% if @post.author == current_user or current_user.admin == true %>
						<%= link_to "X", post_path(@post), method: :delete, class: "btn btn-light btn-sm"%>
						<%= button_tag "Edit", class: "btn btn-light btn-sm"%>
					<% end %>
				</div>
			</div>
			<!-- todo 若使用者是該文章/回覆的作者，在本頁面可以同步進行編輯和刪除-->
		</div>
	</div>
	<hr>
	<!-- Comments if any -->
	<% @comments.each do |c| %>
	<div class="row post_show_comment">
		<div class="col-md-2 post_show_user " id="<%= c.user.id %>" >
			<%= render partial: "shared/user_icon", locals: { user: c.user, related_user: current_user} %>
		</div>
		<div class="col-md-10">
			<div class="row">
				<div class="col-md-10"><%= c.content %></div>
				<div class="col-md-2">
				<% if c.user == current_user or current_user.admin == true %>
					<%= link_to "X", comment_path(c), method: :delete, class: "btn btn-light btn-sm"%>
					<%= button_tag "Edit", class: "btn btn-light btn-sm"%>
				<% end %>
			</div>
			</div>
		</div>
	</div>
	<%end%>
	<!-- Comment area -->
	<div class="row">
		<div class="col-md-2"></div>
		<div class="col-md-10">
			<div class="row">
				<div class="col-md-10 post_show_comment">
					<%= form_with url: post_comments_path(@post, action: 'create'), method: "post" do |form| %>
						<%= form.text_field :content, class: :comment_input%>
						<%= form.submit "Comment" %>
					<% end %>
				</div>
				<div class="col-md-2"></div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(".accept-invitation").on("click", function(event) {
		var id = event.target.parentNode.id;
		$.ajax({
			url: "/users/" + id +"/accept_friendship" ,
			method: "PATCH",
			dataType: "json",
			success: function(){
				// $("#" +id).remove();
				// console.log("Card removed");
				$(".button-"+id).addClass("disabled");
			}
		});
	});

	$(".collect-post").on("click", function(event) {
		var id = event.target.parentNode.id;
		$.ajax({
			url: "/posts/" + id + "/add_collection",
			method: "POST",
			dataType: "json",
			success: function(){
				$(".collect-post").addClass("disabled");
			}
		});
	});

	$(".uncollect-post").on("click", function(event) {
		var id = event.target.parentNode.id;
		$.ajax({
			url: "/posts/" + id + "/remove_collection",
			method: "DELETE",
			dataType: "json",
			success: function(){
				$(".uncollect-post").addClass("disabled");
			}
		});
	});
</script>