config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: "posts#index"

  resources :users, only: [:show, :edit, :update] do 
    member do 
      patch :accept_friendship
    end
  end

  resources :posts do
  	resources :comments, shallow: true
  	member do 
  		post :add_collection
  		delete :remove_collection
    end
    collection do
      get :feeds
    end
  end

  resources :friendships, only: [:create, :destroy]

  scope '/admin' do
    resources :categories, only: [:index, :create, :update, :destroy]
    patch '/users/:id', to: 'users#update_admin', as: :update_admin
    get '/users', to: 'users#index'
    # resources :users, only: [:index, :update]
  end

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :posts, only: [:index, :show, :create, :update, :destroy]
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>道場</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  		<a class="navbar-brand" href="#">道場</a>
  		<div class="navbar-nav">
  			<%= link_to "Feeds", feeds_posts_path, class: "nav-item nav-link"%>
        <%= link_to "All Posts", posts_path, class: "nav-item nav-link"%>
        <%= link_to "New Post", new_post_path, class: "nav-item nav-link"%>
  		</div>
  		<%if user_signed_in?%>
        <div class="ml-auto">
          <% if current_user.admin?%>
            <li class="nav-item nav-link d-inline-block dropdown">
              <a class="dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Admin</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Category List", categories_path, method: :get, class: "nav-link" %>
                <%= link_to "User List", users_path, method: :get, class: "nav-link" %>
              </ul>
            </li>
          <% end %>
          <%= link_to "My Profile", user_path(current_user), method: :get, class: "nav-item nav-link d-inline-block" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-item nav-link d-inline-block" %>
        </div>
        <%else%>
        <%= link_to "Login", new_user_session_path, class: "nav-item nav-link ml-auto" %>
      <%end%>
  	</nav>
    <% if notice %>
      <div class="container-fluid">
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <strong>Notice!</strong>
          <%= notice %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    <% end %>
    <% if alert %>
      <div class="container-fluid">
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <strong>Alert!</strong>
          <%= alert %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    <% end %>
  	<%= yield %>
  </body>
</html>